Repository aukletio/Auklet-Agent-Java, pull requests merged in 2018-10, with the labels that each got.

#2 Remove PR validation logic
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/post-release.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
Labels: devops

#1 APM-1079 & APM-1484: Add initial Implementation for java exception catching
  .gitignore
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/Util.java
  src/test/java/io/auklet/agent/JavaAgentTest.java
Labels: enhancement

#4 APM-1632: Add Bintray deployment (and other devops changes)
  .circleci/config.yml
  .devops/deploy.sh
  .devops/prep-for-whitesource.sh
  LICENSE
  build.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
Labels: devops

#6 Add duplicate build check
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
  .devops/prep-for-whitesource.sh
Labels: devops

#7 Revise duplicate build check
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
Labels: devops

#8 Fix duplicate build check
  .devops/duplicateBuildCheck.sh
Labels: devops

#9 Enhance duplicate build check
  .devops/duplicateBuildCheck.sh
Labels: devops

#10 Do duplicate build check before tagging
  .circleci/config.yml
Labels: devops

#11 Fix duplicate build check again
  .devops/duplicateBuildCheck.sh
Labels: devops

#12 Fix duplicate build check exit logic
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
Labels: devops

#13 Fix duplicate build check exit logic again
  .circleci/config.yml
Labels: devops

#14 Fix duplicate build check exit logic yet again
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
Labels: devops

#3 Release Candidate Review
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/deploy.sh
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
  .devops/post-release.sh
  .devops/prep-for-whitesource.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .gitignore
  LICENSE
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/Util.java
  src/test/java/io/auklet/agent/JavaAgentTest.java
Labels: release

#15 Initial Production Release
  .circleci/config.yml
  .devops/calculate-app-version.sh
  .devops/deploy.sh
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
  .devops/post-release.sh
  .devops/prep-for-whitesource.sh
  .devops/validate-pr.sh
  .devops/validatePr.js
  .gitignore
  LICENSE
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/Util.java
  src/test/java/io/auklet/agent/JavaAgentTest.java
Labels: release

#16 APM-1484: Store Encrypted Auklet Auth file on the device
  src/main/java/io/auklet/agent/Device.java
Labels: enhancement

#18 Do not fetch loopback network interface to calculate mac address hash
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/Util.java
Labels: bug

#19 Downgrade to CircleCI 2.0
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
Labels: devops

#17 Release Candidate Review
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
  build.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/SystemMetrics.java
  src/main/java/io/auklet/agent/Util.java
Labels: release

#21 Remove dependency on Oshi-core package for getting system memory
  build.gradle
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/SystemMetrics.java
Labels: bug

#22 Release Candidate Review
  build.gradle
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/SystemMetrics.java
Labels: release

#20 Release Review
  .circleci/config.yml
  .devops/duplicateBuildCheck.sh
  .devops/flagBuilds.sh
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/SystemMetrics.java
  src/main/java/io/auklet/agent/Util.java
Labels: release

#23 Add more error handling
  README.md
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Util.java
Labels: bug

#24 Release Candidate Review
  README.md
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Util.java
Labels: release

#25 APM-1645: Add custom logging of handled exception events
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
Labels: enhancement

#26 Release Review
  README.md
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Util.java
Labels: release
