Repository aukletio/Auklet-Agent-Java, pull requests merged in 2018-11, with the labels that each got.

#31 APM-1673: Replace simple-json with JSON-Java
  build.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/SystemMetrics.java
  src/main/java/io/auklet/agent/Util.java
Labels: enhancement

#34 Update instructions for bug reports
  README.md
Labels: devops

#29 APM-1649: Add slf4j logging in Auklet agent code
  build.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/SystemMetrics.java
  src/main/java/io/auklet/agent/Util.java
Labels: bug

#27 Release Candidate Review
  README.md
  build.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/SystemMetrics.java
  src/main/java/io/auklet/agent/Util.java
Labels: release

#32 APM-1605: Device Configuration Integration
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/DataRetention.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
Labels: enhancement

#37 APM-1643: add Code Climate/SonarJava for static analysis
  .codeclimate.yml
  .gitignore
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/DataRetention.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/MQTT.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/SystemMetrics.java
  src/main/java/io/auklet/agent/Util.java
Labels: devops

#33 APM-1668: Java USB Communication
  build.gradle
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/Util.java
  src/main/java/io/auklet/agent/broker/Client.java
  src/main/java/io/auklet/agent/broker/MQTTClient.java
  src/main/java/io/auklet/agent/broker/SerialClient.java
Labels: enhancement
