Repository aukletio/Auklet-Agent-Java, pull requests merged in 2019-01, with the labels that each got.

#43 APM-1695: Refactor codebase
  .circleci/config.yml
  .codeclimate.yml
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/io/auklet/Auklet.java
  src/main/java/io/auklet/AukletException.java
  src/main/java/io/auklet/Config.java
  src/main/java/io/auklet/agent/Auklet.java
  src/main/java/io/auklet/agent/AukletExceptionHandler.java
  src/main/java/io/auklet/agent/DataRetention.java
  src/main/java/io/auklet/agent/Device.java
  src/main/java/io/auklet/agent/Messages.java
  src/main/java/io/auklet/agent/SystemMetrics.java
  src/main/java/io/auklet/agent/Util.java
  src/main/java/io/auklet/agent/broker/Client.java
  src/main/java/io/auklet/agent/broker/MQTTClient.java
  src/main/java/io/auklet/agent/broker/SerialClient.java
  src/main/java/io/auklet/config/AbstractConfigFile.java
  src/main/java/io/auklet/config/AbstractConfigFileFromApi.java
  src/main/java/io/auklet/config/AbstractJsonConfigFileFromApi.java
  src/main/java/io/auklet/config/AukletIoBrokers.java
  src/main/java/io/auklet/config/AukletIoCert.java
  src/main/java/io/auklet/config/DataUsageLimit.java
  src/main/java/io/auklet/config/DataUsageTracker.java
  src/main/java/io/auklet/config/DeviceAuth.java
  src/main/java/io/auklet/config/package-info.java
  src/main/java/io/auklet/core/AukletApi.java
  src/main/java/io/auklet/core/DataUsageConfig.java
  src/main/java/io/auklet/core/DataUsageMonitor.java
  src/main/java/io/auklet/core/HasAgent.java
  src/main/java/io/auklet/core/PahoLogger.java
  src/main/java/io/auklet/core/Util.java
  src/main/java/io/auklet/core/package-info.java
  src/main/java/io/auklet/jvm/AukletExceptionHandler.java
  src/main/java/io/auklet/jvm/OSMX.java
  src/main/java/io/auklet/jvm/package-info.java
  src/main/java/io/auklet/package-info.java
  src/main/java/io/auklet/sink/AbstractSink.java
  src/main/java/io/auklet/sink/AukletIoSink.java
  src/main/java/io/auklet/sink/SerialPortSink.java
  src/main/java/io/auklet/sink/Sink.java
  src/main/java/io/auklet/sink/package-info.java
  src/main/resources/io/auklet/config/AukletIoBrokers.schema.json
  src/main/resources/io/auklet/config/DataUsageLimit.schema.json
  src/main/resources/io/auklet/config/DataUsageTracker.schema.json
  src/main/resources/io/auklet/config/DeviceAuth.schema.json
  src/module-info/java/io/auklet/module-info.java
  src/test/java/io/auklet/JavaAgentTest.java
Labels: enhancement

#45 Fix WhiteSource analysis
  .devops/whitesource.sh
  whitesource.cfg
Labels: devops

#46 Remove WhiteSource gradle plugin
  build.gradle
Labels: devops

#47 Miscellaneous bugfixes
  src/main/java/io/auklet/config/DataUsageTracker.java
  src/main/java/io/auklet/sink/AukletIoSink.java
Labels: bug

#49 Log base URL during agent init
  src/main/java/io/auklet/Auklet.java
Labels: enhancement

#50 Remove Optional shim library
  build.gradle
  src/main/java/io/auklet/jvm/OSMX.java
  src/main/java/io/auklet/sink/AbstractSink.java
Labels: enhancement

#51 APM-1674: Add Message Key
  src/main/java/io/auklet/sink/AbstractSink.java
Labels: enhancement

#48 APM-1724: Add support for Android
  .codeclimate.yml
  README.md
  build.gradle
  src/main/java/io/auklet/Auklet.java
  src/main/java/io/auklet/Config.java
  src/main/java/io/auklet/config/AbstractConfigFileFromApi.java
  src/main/java/io/auklet/config/AbstractJsonConfigFileFromApi.java
  src/main/java/io/auklet/config/AukletIoBrokers.java
  src/main/java/io/auklet/config/AukletIoCert.java
  src/main/java/io/auklet/config/DataUsageLimit.java
  src/main/java/io/auklet/config/DataUsageTracker.java
  src/main/java/io/auklet/config/DeviceAuth.java
  src/main/java/io/auklet/core/AukletApi.java
  src/main/java/io/auklet/core/AukletExceptionHandler.java
  src/main/java/io/auklet/jvm/package-info.java
  src/main/java/io/auklet/misc/AukletDaemonExecutor.java
  src/main/java/io/auklet/misc/PahoLogger.java
  src/main/java/io/auklet/misc/Util.java
  src/main/java/io/auklet/misc/package-info.java
  src/main/java/io/auklet/platform/AbstractPlatform.java
  src/main/java/io/auklet/platform/AndroidPlatform.java
  src/main/java/io/auklet/platform/JavaPlatform.java
  src/main/java/io/auklet/platform/Platform.java
  src/main/java/io/auklet/platform/metrics/AndroidMetrics.java
  src/main/java/io/auklet/platform/metrics/OSMX.java
  src/main/java/io/auklet/platform/metrics/package-info.java
  src/main/java/io/auklet/platform/package-info.java
  src/main/java/io/auklet/sink/AbstractSink.java
  src/main/java/io/auklet/sink/AukletIoSink.java
Labels: enhancement

#53 Remove shadow JAR plugin
  build.gradle
Labels: devops

#54 Make init/shutdown more defensive
  src/main/java/io/auklet/Auklet.java
  src/main/java/io/auklet/core/AukletApi.java
  src/main/java/io/auklet/sink/AukletIoSink.java
  src/main/java/io/auklet/sink/Sink.java
Labels: bug
